# Generated by Django 4.0.3 on 2022-05-11 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('fees', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('instructor', models.CharField(max_length=255)),
                ('img_url', models.CharField(max_length=2083)),
            ],
        ),
    ]
