# Generated by Django 4.0.3 on 2022-03-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_courses_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='image_url',
            field=models.CharField(default='', max_length=2083),
        ),
    ]
